name: Build and Release CodeWalker API
on:
  push:
    tags:
      - "v*"  # Runs when a version tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: windows-latest  # Windows is required for CodeWalker
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Debug - List Files Before Cloning
        run: ls -R

      - name: Clone Only CodeWalker.Core Into ${{ github.workspace }}/CodeWalker.Core
        run: |
          git init CodeWalker.Core
          cd CodeWalker.Core
          git remote add origin https://github.com/dexyfex/CodeWalker.git
          git config core.sparseCheckout true
          echo "CodeWalker.Core/" >> .git/info/sparse-checkout
          git pull origin master --depth=1
          cd ..

      - name: Debug - List Files After Cloning
        run: ls -R

      - name: Verify CodeWalker.Core Exists
        shell: pwsh
        run: |
          if (!(Test-Path "${{ github.workspace }}/CodeWalker.Core/CodeWalker.Core.csproj")) {
            Write-Host "❌ CodeWalker.Core is missing!"
            exit 1
          } else {
            Write-Host "✅ CodeWalker.Core is present."
          }

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore "${{ github.workspace }}/CodeWalker.API/CodeWalker.API.csproj"

      - name: Build CodeWalker.API
        run: |
          cd "${{ github.workspace }}/CodeWalker.API"
          msbuild CodeWalker.API.csproj /p:Configuration=Release

      - name: Archive the built files
        run: |
          mkdir build-output
          xcopy /E /I "${{ github.workspace }}/CodeWalker.API/bin/Release" build-output

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-output/*
          token: ${{ secrets.RELEASE_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
