name: Build and Release CodeWalker API

on:
  push:
    tags:
      - "v*" # Runs when a version tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: windows-latest # Windows required for CodeWalker

    steps:
      - name: Checkout CodeWalker.API Repo
        uses: actions/checkout@v4
        with:
          path: CodeWalker.API # Clones into ${{ github.workspace }}/CodeWalker.API

      - name: Clone Full CodeWalker Repo (for CodeWalker.Core)
        run: |
          git clone --depth=1 https://github.com/dexyfex/CodeWalker.git "${{ github.workspace }}/CodeWalkerRepo"

      - name: Move CodeWalker.Core to Workdirectory
        run: |
          move "${{ github.workspace }}\CodeWalkerRepo\CodeWalker.Core" "${{ github.workspace }}"

      - name: Verify CodeWalker.Core Exists
        shell: pwsh
        run: |
          if (!(Test-Path "${{ github.workspace }}/CodeWalker.Core/CodeWalker.Core.csproj")) {
            Write-Host "❌ CodeWalker.Core is missing!"
            exit 1
          } else {
            Write-Host "✅ CodeWalker.Core is present."
          }

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages
        run: |
          nuget restore "${{ github.workspace }}/CodeWalker.Core/CodeWalker.Core.csproj"
          nuget restore "${{ github.workspace }}/CodeWalker.API/CodeWalker.API.csproj"

      - name: Publish CodeWalker.API (non-single-file)
        run: |
          cd "${{ github.workspace }}/CodeWalker.API"
          dotnet publish -c Release -r win-x64 --self-contained true


      - name: Package published output as ZIP
        shell: cmd
        run: |
            @echo on
            set PUBLISH_DIR=${{ github.workspace }}\CodeWalker.API\bin\Release\net9.0\win-x64\publish
            set OUTPUT_ZIP=${{ github.workspace }}\CodeWalker.API.zip
            echo "Zipping full publish directory..."
            powershell Compress-Archive -Path "%PUBLISH_DIR%\*" -DestinationPath "%OUTPUT_ZIP%"
            if not exist "%OUTPUT_ZIP%" (
                echo "❌ ERROR: ZIP file was not created!"
                exit 1
            ) else (
                echo "✅ ZIP file created successfully."
            )



      - name: Debug - List Workspace Contents
        shell: cmd
        run: |
          @echo on
          dir /s "${{ github.workspace }}"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ github.workspace }}/CodeWalker.API.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
