name: Build and Release CodeWalker API
on:
  push:
    tags:
      - "v*"  # Runs when a version tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: windows-latest  # Windows is required for CodeWalker
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -R

      - name: Download CodeWalker source
        run: git clone --recursive https://github.com/dexyfex/CodeWalker.git "${{ github.workspace }}/CodeWalker"

      - name: Verify CodeWalker.Core Exists
        shell: pwsh
        run: |
          if (!(Test-Path "${{ github.workspace }}/CodeWalker/CodeWalker.Core/CodeWalker.Core.csproj")) {
            Write-Host "❌ CodeWalker.Core is missing!"
            exit 1
          } else {
            Write-Host "✅ CodeWalker.Core is present."
          }

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore "${{ github.workspace }}/CodeWalker/CodeWalker.sln"

      - name: Build CodeWalker.Core
        run: |
          cd "${{ github.workspace }}/CodeWalker/CodeWalker.Core"
          msbuild CodeWalker.Core.csproj /p:Configuration=Release

      - name: Build CodeWalker.API
        run: |
          cd "${{ github.workspace }}/CodeWalker.API"
          msbuild CodeWalker.API.csproj /p:Configuration=Release

      - name: Archive the built files
        run: |
          mkdir build-output
          xcopy /E /I "${{ github.workspace }}/CodeWalker.API/bin/Release" build-output

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-output/*
          token: ${{ secrets.RELEASE_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
